steps:
  # Build the container image with BuildKit enabled
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/n8n/n8n:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/n8n/n8n:latest', '-f', 'docker/images/n8n/Dockerfile', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/n8n/n8n:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/n8n/n8n:latest']

timeout: 1800s  # 30 minutes

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/n8n/n8n:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/n8n/n8n:latest'
