version: '3.8'

services:
  n8n:
    # image: ghcr.io/erol-guney/n8n:latest
    image: n8nio/n8n:local
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Basic Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=n8n_password
      
      # Database (using SQLite for simplicity)
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      
      # General Settings
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      
      # Security
      - N8N_ENCRYPTION_KEY=your-encryption-key-change-this
      
      # Webhook URL (adjust if needed)
      - WEBHOOK_URL=http://localhost:5678/
      
      # Disable credential sharing (set to 'true' to disable)
      - N8N_DISABLE_CREDENTIAL_SHARING=true
      
    volumes:
      # Persist n8n data
      - n8n_data:/home/node/.n8n
      
      # Mount local files if needed for custom nodes
      # - ./custom-nodes:/home/node/.n8n/custom
      
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:
    driver: local
