volumes:
  postgres-data:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../:/workspaces
      - /Users/ozlevka/.ssh:/home/node/.ssh:ro
      - /Users/ozlevka/.n8n:/home/node/.n8n
    environment:
      - POSTGRES_DB=n8n
    
    

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    environment:
      DB_POSTGRESDB_HOST: postgres
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PASSWORD: password
