name: Reusable linting workflow

on:
  workflow_call:
    inputs:
      ref:
        description: GitHub ref to lint.
        required: false
        type: string
        default: master
      cacheKey:
        description: Cache key for modules and build artifacts.
        required: false
        default: ''
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Setup corepack and pnpm
        run: |
          npm i -g corepack@0.31
          corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache build artifacts
        uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            ./packages/**/dist
            ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ inputs.cacheKey || github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: pnpm build

      - name: Lint Backend
        run: pnpm lint:backend

      - name: Lint Nodes
        run: pnpm lint:nodes

      - name: Lint Frontend
        run: pnpm lint:frontend
