name: Notify PR status changed

on:
  pull_request_review:
    types: [submitted, dismissed]
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') ||
      (github.event_name == 'pull_request_review' && github.event.review.state == 'dismissed') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == false && github.event.action == 'closed')
    steps:
      - name: Notify Feishu
        if: ${{!contains(github.event.pull_request.labels.*.name, 'community')}}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "msg_type": "text",
            "content": {
              "text": "PR 状态变更通知\nPR标题: ${{ github.event.pull_request.title }}\nPR链接: ${{ github.event.pull_request.html_url }}\n状态: ${{ github.event.review.state || 'closed' }}\n操作人: ${{ github.actor }}\n仓库: ${{ github.repository }}"
            }
          }' \
          ${{ secrets.FEISHU_WEBHOOK_URL }}
